name = "Snake v1.0"

[store]
id="com.github.M4ss1ck.snake"
version_name=1.0
version_code=1
author="M4ss1ck"
author_email="massick@systemli.org"
description="Help the snake eat and grow, but be careful not to bite yourself!"